<html>

<head>
    <title>This Email generated by www.codechief.org</title>
</head>

<body>
    <p>Hi <strong>user</strong>, your order has been dispatched to a fleet and is currently on transit
    </p>
</body>

</html>
